name: abiword-gtk
base: core22
version: '3.0.5'
summary: Word Processing for Everyone...
description: |
  Lightweight and Opensource Powerful Word processing Software built with Gtk3.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64

    
slots:
  abiword-gtk:
    interface: dbus
    bus: session
    name: io.github.cc23.abiword

apps:
  abiword-gtk:
    command: usr/bin/abiword
    extensions: [gnome]
    common-id: org.community.abiword
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - network-status
      - network
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  abiword:
    source: https://www.abisource.com/downloads/abiword/3.0.5/source/abiword-3.0.5.tar.gz
    plugin: autotools
    build-packages:
      - gsfonts
      - libdbus-1-3
      - libdbus-glib-1-2
      - libgcc-s1
      - libgcrypt20
      - libglib2.0-0
      - libgnutls30
      - libgoffice-0.10-10
      - libgsf-1-114
      - libgtk-3-0
      - libjpeg8
      - libloudmouth1-0
      - libots0
      - libpng-dev
      - libpng16-16
      - librdf0
      - libreadline8
      - librevenge-0.0-0
      - libsoup2.4-1
      - libstdc++6
      - libtelepathy-glib0
      - libtidy5deb1
      - libwmf0.2-7
      - libwpd-0.10-10
      - libwpg-0.3-3
      - libxml2
      - zlib1g
      - poppler-utils
  
  
