name: abiword-gtk
base: core22
version: '3.0.5'
summary: Word Processing for Everyone...
description: |
  Lightweight and Opensource Powerful Word processing Software built with Gtk3.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
                
apps:
  abiword-gtk:
    command: usr/bin/abiword
    extensions: [gnome]
    common-id: org.community.abiword
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - network-status
      - network
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  abiword:
    source: https://www.abisource.com/downloads/abiword/3.0.5/source/abiword-3.0.5.tar.gz
    plugin: make
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - autotools-dev
      - automake
      - autoconf
      - autopoint
      - libtool
      - libtool-bin
      - pkg-config
      - intltool
      - libcurl4-openssl-dev
      - libglib2.0-dev
      - libevent-dev
      - libminiupnpc-dev
      - libgtk-3-dev
      - libappindicator3-dev
      - libssl-dev
      - libgdk-pixbuf-2.0-0
      - libgdk-pixbuf2.0-common
      - libgdk-pixbuf2.0-bin
      
  
  
